// Generated by gencpp from file week_4_exercises/MyMessage.msg
// DO NOT EDIT!


#ifndef WEEK_4_EXERCISES_MESSAGE_MYMESSAGE_H
#define WEEK_4_EXERCISES_MESSAGE_MYMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace week_4_exercises
{
template <class ContainerAllocator>
struct MyMessage_
{
  typedef MyMessage_<ContainerAllocator> Type;

  MyMessage_()
    : header()
    , sine()
    , cosine()  {
    }
  MyMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sine(_alloc)
    , cosine(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _sine_type;
  _sine_type sine;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _cosine_type;
  _cosine_type cosine;





  typedef boost::shared_ptr< ::week_4_exercises::MyMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::week_4_exercises::MyMessage_<ContainerAllocator> const> ConstPtr;

}; // struct MyMessage_

typedef ::week_4_exercises::MyMessage_<std::allocator<void> > MyMessage;

typedef boost::shared_ptr< ::week_4_exercises::MyMessage > MyMessagePtr;
typedef boost::shared_ptr< ::week_4_exercises::MyMessage const> MyMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::week_4_exercises::MyMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::week_4_exercises::MyMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::week_4_exercises::MyMessage_<ContainerAllocator1> & lhs, const ::week_4_exercises::MyMessage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sine == rhs.sine &&
    lhs.cosine == rhs.cosine;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::week_4_exercises::MyMessage_<ContainerAllocator1> & lhs, const ::week_4_exercises::MyMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace week_4_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::week_4_exercises::MyMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::week_4_exercises::MyMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::week_4_exercises::MyMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::week_4_exercises::MyMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::week_4_exercises::MyMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::week_4_exercises::MyMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::week_4_exercises::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a281917cf9fec5956d6c0f08ed9f721";
  }

  static const char* value(const ::week_4_exercises::MyMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a281917cf9fec59ULL;
  static const uint64_t static_value2 = 0x56d6c0f08ed9f721ULL;
};

template<class ContainerAllocator>
struct DataType< ::week_4_exercises::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "week_4_exercises/MyMessage";
  }

  static const char* value(const ::week_4_exercises::MyMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::week_4_exercises::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Float64 sine\n"
"std_msgs/Float64 cosine\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::week_4_exercises::MyMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::week_4_exercises::MyMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sine);
      stream.next(m.cosine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::week_4_exercises::MyMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::week_4_exercises::MyMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sine: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.sine);
    s << indent << "cosine: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.cosine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEEK_4_EXERCISES_MESSAGE_MYMESSAGE_H
